### ISSUE TITLE
ResumeBoost简历生成器

### ISSUE THREAD

**Issue by fuji246** [yzfly/wonderful-prompts#2]
特色功能:

1. 定制的简历指导，以适应您独特的领域，风格和经验水平。

2. 收集关键信息，包括工作历史、成就、教育背景和技能，以帮助个性化创建简历。

3. 收集任何额外的信息，完美呈现您的专业资质。

4. 根据申请的职位描述，以整合相关的关键词和短语，打造符合ATS（求职者跟踪系统）标准的简历。

5. markdown格式的简历，包括引人注目的摘要、技术技能列表和软技能展示。

6. 根据提供的职位描述评估简历，并分配0到100的得分，反映其与职位要求的一致性。

要开始创建个性化简历，只需键入/start，如果需要修改偏好，如行业或语气风格，请使用/config命令。

想了解特定职位的简历样本，可使用/example命令并提供职位描述。

https://github.com/MrResume/ResumeBoost/

**Comment by yzfly** [comment]
很棒，已收录，感谢分享！
